export const LOAD_POST_USER = "[POST] LOAD_POST_USER";
export const LOAD_PENDING_POST_USER = "[POST] LOAD_PENDING_POST_USER";
export const LOAD_RESOLVED_POST_USER = "[POST] LOAD_RESOLVED_POST_USER";
export const UPDATE_POST_OFFERED = "[POST] UPDATE_POST_OFFERED";
export const LOAD_POST_PROFESSIONAL = "[POST] LOAD_POST_PROFESSIONAL";
